export const spacesData = [
  {
    id: 1,
    categories: ["Fundraising"],
    image: "/featured-projects/wck.avif",
    date: "Ramadan 2024",
    name: "World Central Kitchen",
    location: "Multi-Million Dollar Fundraising",
    clientImage: "/featured-projects/wck.avif",
    clientName: "World Central Kitchen",
    route: "/projects/world-central-kitchen",
  },
  {
    id: 2,
    categories: ["Branding", "Fundraising"],
    image: "/featured-projects/mlfa.jpg",
    date: "2023 - Present",
    name: "Muslim Legal Fund of America",
    location: "1000% ROI on SEM Campaigns",
    clientImage: "/featured-projects/mlfa.jpg",
    clientName: "MLFA",
    route: "/projects/mlfa",
  },
  {
    id: 3,
    categories: ["Branding"],
    image: "/featured-projects/qahwah-house-5.jpeg",
    date: "2024",
    name: "Qahwah House",
    location: "National Brand Expansion",
    clientImage: "/featured-projects/qahwah-house-5.jpeg",
    clientName: "Qahwah House Coffee",
    route: "/projects/qahwah-house",
  },
  {
    id: 4,
    categories: ["Storytelling"],
    image: "/featured-projects/seenp.webp",
    date: "2024",
    name: "Seen TV Palestine",
    location: "Coast-to-Coast Film Tour",
    clientImage: "/featured-projects/seenp.webp",
    clientName: "Seen TV",
    route: "/projects/seen-tv",
  }
];